spring:
  cloud:
    stream:
      bindings:
        greetings-in:
          destination: kafka-first-test
          group: spring-boot-kafka-sample
          contentType: application/json
        greetings-out:
          destination: kafka-first-test
          group: spring-boot-kafka-sample
          contentType: application/json